### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by miguellavalle** [pearofducks/ansible-vim#74] opened 2019-03-28 21:09 UTC
what config do you use to get this highlighting: https://camo.githubusercontent.com/6f304717cef61cba73b61ba73444d143e3b1ebc6/687474703a2f2f692e696d6775722e636f6d2f7768424f5a5a4b2e706e67?

I get almost no highlighting

**Comment by pearofducks** [comment] 2019-03-29 07:17
You should only need the solarized colorscheme and a few specific options set for this plugin to get highlighting like that.

I'd suggest [solarized8](https://github.com/lifepillar/vim-solarized8), and then as mentioned above that screenshot, there are some 'bright/selective' options set such as:

```
let g:ansible_attribute_highlight = "ob"
let g:ansible_name_highlight = 'b'
```

If you're able to reproduce any highlighting bugs with a minimal vimrc please feel free to post here and I'll look into it if it reproduces on my instances of Vim!

**Comment by miguellavalle** [comment] 2019-03-29 16:54
Thanks for your quick response. I followed your recommendation. Still getting very litlle highlighting. I am using iterm2 and this is my .vimrc:

set tabstop=8
set expandtab
set shiftwidth=4
set softtabstop=4
set textwidth=79
syntax on
syntax enable
filetype on
filetype plugin indent on
set autoindent
set nu
set ruler
set tags=.git/tags
execute pathogen#infect()
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType java set omnifunc=javacomplete#Complete
let g:syntastic_auto_loc_list=1
let g:syntastic_python_checkers=['flake8']
let g:Tlist_Use_Right_Window=1
let g:Tlist_Ctags_Cmd='/usr/local/bin/ctags'
let g:ansible_attribute_highlight = "ab"
let g:ansible_name_highlight = 'b'
nnoremap <silent> <F2> :cd %:p:h<cr>
nnoremap <silent> <F3> :TagbarToggle<CR>
nnoremap <silent> <F4> :set hlsearch<CR>
nnoremap <silent> <F5> :set nohlsearch<CR>
nnoremap <silent> <F6> :let _s=@/ <Bar> :%s/\s\+$//e <Bar> :let @/=_s <Bar> :nohl <Bar> :unlet _s <CR>
set laststatus=2
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P
set termguicolors
set background=dark
color solarized8_high

**Comment by pearofducks** [comment] 2019-03-30 13:33
I'm not able to reproduce any problems on my side across multiple OSes and Vim versions - including iterm2 on Mac.

I suspect this is a configuration issue on your end, but I'm not able to offer support for that, my focus is on ensuring this plugin is bug free.

I'm closing this issue but please feel free to open a new one should you find a root cause that implicates this plugin.

**Closed by pearofducks** 2019-03-30 13:33 UTC
