### ISSUE TITLE
Indentation not working as expected

### ISSUE THREAD

**Issue by flaugher** [pearofducks/ansible-vim#5] opened 2016-01-01 00:30 UTC
If I have your plugin installed and I type the following code into a .yml playbook file,

- name: blah
  tasks:
    - name: blah blah
    copy:        " This indents left when I type the colon

When I begin typing "copy" it gets indented in line with "name" above it as it should.  But as soon as I type the closing ":", the line indents out so that copy is aligned with the dash in front of name instead of remaining indented in line with "name".  Should it work that way?  I believe the "name" and "copy" should be aligned.  Do I perhaps have to have something else set in my .vimrc file in order for the indentation to work properly?

Thanks.

**Comment by pearofducks** [comment] 2016-01-01 10:06
I can't reproduce this with a blank `playbook.yml`. Have you tried running against a minimal .vimrc to reproduce?

Also I'm guessing the code you provided is just an example of the structure? (BTW: You can wrap your code in three backticks ` in markdown, and it will format properly)

**Comment by flaugher** [comment] 2016-01-01 19:58
Hi Dave,

Thanks for your response.  No, I haven’t tried running it against a blank .vimrc but that’s a good idea.  For now, I’ve just switched to writing my Ansible playbooks in Sublime Text.

Robert

**Comment by pearofducks** [comment] 2016-01-04 14:24
OK, I'll close this for now, but if you do find something concrete let me know!

**Closed by pearofducks** 2016-01-04 14:24 UTC
